--- #YAML:1.0
name:                Ruby
version:             0.07
abstract:            'Perl interface to Ruby interpreter'
license:             perl
author:              '
    - Goro Fuji'
generated_by:        'ExtUtils::MakeMaker version 6.44'
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
